# Generated by Django 2.0.1 on 2018-01-15 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0003_auto_20180115_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='owner',
            new_name='admin',
        ),
    ]
