# Generated by Django 2.0.1 on 2018-01-15 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0004_auto_20180115_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='admin',
            new_name='owner',
        ),
    ]
